import { Language, DisplayMode, Settings, UserData } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    chooseLanguage: "Choose your language",
    pickLanguage: "Pick the language you're most comfortable with",
    continue: "Continue",
    privacyMatters: "Your Privacy Matters",
    privacyDesc: "Quick Math is designed with privacy at its core.",
    offline: "Works fully offline after setup",
    ageLimit: "You must be 18 or older to use this app",
    noData: "Zero personal data collected or shared",
    acceptContinue: "Accept & Continue",
    sessionDuration: "Session Duration",
    oneCardEvery: "One card every",
    strictMode: "Strict Mode",
    premium: "Premium",
    slideToStart: "Slide to Start",
    startSession: "Start Session",
    stopSession: "Stop Session",
    doubleTapToStart: "Double-tap the QM logo above",
    doubleTapToStop: "Active — double-tap to stop",
    share: "Share",
    contactUs: "Contact Us",
    feedback: "Feedback",
    aboutUs: "About Us",
    settings: "Settings",
    save: "Save",
    displayMode: "DISPLAY MODE",
    halfScreen: "Half Screen",
    fullScreen: "Full Screen",
    session: "SESSION",
    audioCue: "Audio Cue",
    vibration: "Vibration",
    funPopups: "FUN POP-UPS",
    problemsBeforePopup: "Problems before pop-up",
    language: "Language",
    cardDuration: "CARD DURATION",
    answerTime: "Answer Time per Card",
    choosePlan: "Choose Your Plan",
    trialIncluded: "3-day free trial included",
    noAds: "No Ads",
    leaderboards: "Leaderboards (coming soon)",
    prioritySupport: "Priority Support",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    billedWeekly: "Billed ₹21/week",
    billedMonthly: "Billed monthly",
    billedAnnually: "Billed annually",
    joinPremium: "Join Premium",
    restorePurchase: "Restore Purchase",
    bestValue: "Best Value",
    thinkQuick: "Think quick!",
    trialActive: "Free Trial Active — {days} days left",
    trialDesc: "All premium features unlocked. Verify your number to keep access after trial.",
    upgrade: "Upgrade",
    overlayPermission: "Overlay permission not granted. Math cards won't appear over other apps.",
    restoreTitle: "Restore Purchase",
    restoreDesc: "Please contact support at nophonekidz@gmail.com with your payment receipt.",
    upiNotAvailable: "UPI not available",
    upiDesc: "Please install GPay, PhonePe or any UPI app, or contact support at nophonekidz@gmail.com",
    ok: "OK",
    version: "Version 1.0.0",
    aboutDesc: "Quick Math keeps your mind sharp by showing math problems as overlays during your daily phone usage.",
    madeWithCare: "Made with care for sharp minds"
  },
  te: {
    chooseLanguage: "మీ భాషను ఎంచుకోండి",
    pickLanguage: "మీకు అత్యంత సౌకర్యవంతమైన భాషను ఎంచుకోండి",
    continue: "కొనసాగించు",
    privacyMatters: "మీ గోప్యత ముఖ్యం",
    privacyDesc: "క్విక్ మ్యాథ్ గోప్యతను దృష్టిలో ఉంచుకుని రూపొందించబడింది.",
    offline: "సెటప్ తర్వాత పూర్తిగా ఆఫ్ లైన్ లో పనిచేస్తుంది",
    ageLimit: "ఈ యాప్‌ను ఉపయోగించడానికి మీకు 18 ఏళ్లు లేదా అంతకంటే ఎక్కువ వయస్సు ఉండాలి",
    noData: "వ్యక్తిగత డేటా సేకరించబడదు లేదా భాగస్వామ్యం చేయబడదు",
    acceptContinue: "అంగీకరించండి & కొనసాగించండి",
    sessionDuration: "సెషన్ వ్యవధి",
    oneCardEvery: "ప్రతి కార్డ్",
    strictMode: "కఠిన మోడ్",
    premium: "ప్రీమియం",
    slideToStart: "ప్రారంభించడానికి స్లైడ్ చేయండి",
    startSession: "సెషన్ ప్రారంభించండి",
    stopSession: "సెషన్ ఆపండి",
    doubleTapToStart: "పైన ఉన్న QM లోగోను డబుల్ ట్యాప్ చేయండి",
    doubleTapToStop: "యాక్టివ్ — ఆపడానికి డబుల్ ట్యాప్ చేయండి",
    share: "భాగస్వామ్యం",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    feedback: "అభిప్రాయం",
    aboutUs: "మా గురించి",
    settings: "సెట్టింగ్‌లు",
    save: "సేవ్ చేయి",
    displayMode: "ప్రదర్శన మోడ్",
    halfScreen: "సగం స్క్రీన్",
    fullScreen: "పూర్తి స్క్రీన్",
    session: "సెషన్",
    audioCue: "ఆడియో సూచన",
    vibration: "వైబ్రేషన్",
    funPopups: "సరదా పాప్-అప్‌లు",
    problemsBeforePopup: "పాప్-అప్ ముందు సమస్యలు",
    language: "భాష",
    cardDuration: "కార్డ్ వ్యవధి",
    answerTime: "కార్డ్ ప్రతి సమాధాన సమయం",
    choosePlan: "మీ ప్లాన్‌ను ఎంచుకోండి",
    trialIncluded: "3 రోజుల ఉచిత ట్రయల్ చేర్చబడింది",
    noAds: "ప్రకటనలు లేవు",
    leaderboards: "లీడర్‌బోర్డ్‌లు (త్వరలో వస్తుంది)",
    prioritySupport: "ప్రాధాన్యత మద్దతు",
    daily: "రోజువారీ",
    monthly: "నెలవారీ",
    yearly: "వార్షిక",
    billedWeekly: "₹21/వారం బిల్ చేయబడింది",
    billedMonthly: "నెలవారీ బిల్ చేయబడింది",
    billedAnnually: "వార్షికంగా బిల్ చేయబడింది",
    joinPremium: "ప్రీమియంలో చేరండి",
    restorePurchase: "కొనుగోలును పునరుద్ధరించండి",
    bestValue: "ఉత్తమ విలువ",
    thinkQuick: "వేగంగా ఆలోచించండి!",
    trialActive: "ఉచిత ట్రయల్ యాక్టివ్ — {days} రోజులు మిగిలి ఉన్నాయి",
    trialDesc: "అన్ని ప్రీమియం ఫీచర్లు అన్‌లాక్ చేయబడ్డాయి. ట్రయల్ తర్వాత యాక్సెస్ ఉంచడానికి మీ నంబర్‌ను ధృవీకరించండి.",
    upgrade: "అప్‌గ్రేడ్",
    overlayPermission: "ఓవర్‌లే అనుమతి మంజూరు చేయబడలేదు. ఇతర యాప్‌లపై గణిత కార్డ్‌లు కనిపించవు.",
    restoreTitle: "కొనుగోలును పునరుద్ధరించండి",
    restoreDesc: "దయచేసి మీ చెల్లింపు రసీదుతో nophonekidz@gmail.com వద్ద మద్దతును సంప్రదించండి.",
    upiNotAvailable: "UPI అందుబాటులో లేదు",
    upiDesc: "దయచేసి GPay, PhonePe లేదా ఏదైనా UPI యాప్‌ను ఇన్‌స్టాల్ చేయండి లేదా nophonekidz@gmail.com వద్ద మద్దతును సంప్రదించండి",
    ok: "సరే",
    version: "వెర్షన్ 1.0.0",
    aboutDesc: "క్విక్ మ్యాథ్ మీ రోజువారీ ఫోన్ వినియోగం సమయంలో గణిత సమస్యలను ఓవర్‌లేలుగా చూపడం ద్వారా మీ మనస్సును పదునుగా ఉంచుతుంది.",
    madeWithCare: "పదునైన మనస్సుల కోసం శ్రద్ధతో రూపొందించబడింది"
  },
  hi: {
    chooseLanguage: "अपनी भाषा चुनें",
    pickLanguage: "वह भाषा चुनें जिसमें आप सबसे अधिक सहज हों",
    continue: "जारी रखें",
    privacyMatters: "आपकी गोपनीयता मायने रखती है",
    privacyDesc: "क्विक मैथ को गोपनीयता को ध्यान में रखकर बनाया गया है।",
    offline: "सेटअप के बाद पूरी तरह से ऑफलाइन काम करता है",
    ageLimit: "इस ऐप का उपयोग करने के लिए आपकी आयु 18 वर्ष या उससे अधिक होनी चाहिए",
    noData: "शून्य व्यक्तिगत डेटा एकत्र या साझा किया गया",
    acceptContinue: "स्वीकार करें और जारी रखें",
    sessionDuration: "सत्र की अवधि",
    oneCardEvery: "एक कार्ड हर",
    strictMode: "सख्त मोड",
    premium: "प्रीमियम",
    slideToStart: "शुरू करने के लिए स्लाइड करें",
    startSession: "सत्र शुरू करें",
    stopSession: "सत्र रोकें",
    doubleTapToStart: "ऊपर दिए गए QM लोगो को डबल-टैप करें",
    doubleTapToStop: "सक्रिय — रोकने के लिए डबल-टैप करें",
    share: "साझा करें",
    contactUs: "हमसे संपर्क करें",
    feedback: "प्रतिक्रिया",
    aboutUs: "हमारे बारे में",
    settings: "सेटिंग्स",
    save: "सहेजें",
    displayMode: "प्रदर्शन मोड",
    halfScreen: "आधी स्क्रीन",
    fullScreen: "पूरी स्क्रीन",
    session: "सत्र",
    audioCue: "ऑडियो संकेत",
    vibration: "कंपन",
    funPopups: "मज़ेदार पॉप-अप",
    problemsBeforePopup: "पॉप-अप से पहले सवाल",
    language: "भाषा",
    cardDuration: "कार्ड की अवधि",
    answerTime: "प्रति कार्ड उत्तर समय",
    choosePlan: "अपनी योजना चुनें",
    trialIncluded: "3-दिन का निःशुल्क परीक्षण शामिल है",
    noAds: "कोई विज्ञापन नहीं",
    leaderboards: "लीडरबोर्ड (जल्द ही आ रहा है)",
    prioritySupport: "प्राथमिकता सहायता",
    daily: "दैनिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    billedWeekly: "₹21/सप्ताह बिल किया गया",
    billedMonthly: "मासिक बिल किया गया",
    billedAnnually: "सालाना बिल किया गया",
    joinPremium: "प्रीमियम में शामिल हों",
    restorePurchase: "खरीद पुनर्स्थापित करें",
    bestValue: "सबसे अच्छा मूल्य",
    thinkQuick: "जल्दी सोचो!",
    trialActive: "निःशुल्क परीक्षण सक्रिय — {days} दिन शेष",
    trialDesc: "सभी प्रीमियम सुविधाएं अनलॉक हैं। परीक्षण के बाद पहुंच बनाए रखने के लिए अपना नंबर सत्यापित करें.",
    upgrade: "अपग्रेड",
    overlayPermission: "ओवरले अनुमति नहीं दी गई है। गणित कार्ड अन्य ऐप्स के ऊपर दिखाई नहीं देंगे।",
    restoreTitle: "खरीद पुनर्स्थापित करें",
    restoreDesc: "कृपया अपनी भुगतान रसीद के साथ nophonekidz@gmail.com पर सहायता से संपर्क करें।",
    upiNotAvailable: "UPI उपलब्ध नहीं है",
    upiDesc: "कृपया GPay, PhonePe या कोई UPI ऐप इंस्टॉल करें, या nophonekidz@gmail.com पर सहायता से संपर्क करें",
    ok: "ठीक है",
    version: "संस्करण 1.0.0",
    aboutDesc: "क्विक मैथ आपके दैनिक फोन उपयोग के दौरान गणित की समस्याओं को ओवरले के रूप में दिखाकर आपके दिमाग को तेज रखता है।",
    madeWithCare: "तेज दिमागों के लिए सावधानी से बनाया गया"
  }
};

export const DEFAULT_SETTINGS: Settings = {
  displayMode: DisplayMode.HALF,
  cardDuration: 15,
  strictMode: false,
  funPopups: true,
  popupInterval: 2,
  language: Language.EN,
  audioCue: true,
  vibration: true,
  sessionDuration: 20,
  cardFrequency: 1
};

export const INITIAL_USER_DATA: UserData = {
  onboarded: false,
  trialStartedAt: null,
  hasAnyPremium: false,
  otpVerified: false,
  otpSkippedAt: null,
  settings: DEFAULT_SETTINGS
};
